# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json
PackageIdentifier: Envoy49.go-spotify-cli
PackageVersion: 1.0.41
InstallerType: portable
Installers:
  - Architecture: arm64
    InstallerUrl: https://github.com/Envoy49/go-spotify-cli/releases/download/v1.0.63/go-spotify-cli-windows-amd64.exe
    InstallerSha256: 6097FDC51FE098B84DDF80DDEB77D7404B29B9D51C36FDF33A18F8BEF92457E4
  - Architecture: x64
    InstallerUrl: https://github.com/Envoy49/go-spotify-cli/releases/download/v1.0.63/go-spotify-cli-windows-amd64.exe
    InstallerSha256: 6097FDC51FE098B84DDF80DDEB77D7404B29B9D51C36FDF33A18F8BEF92457E4
ManifestType: installer
ManifestVersion: 1.5.0
